#ifndef CONDITIONAL_COMPILATION_CONSTANTS_H
#define CONDITIONAL_COMPILATION_CONSTANTS_H

#define CONTAINERS_FOR_SPEED

#define EXTENDED_RAM_MEMORY_

#define USING_MODULES_

#define SHORTER_CODE

#define USE_OPENGL

#endif
