
#ifndef __SB7COLOR_H__
#define __SB7COLOR_H__

#include <string>
#include <unordered_map>

#include <vmath.h>

namespace sb7
{
    inline vmath::vec3 FromVec4ToVec3(const vmath::vec4& Vector4)
    {
        return {Vector4.data[0], Vector4.data[1], Vector4.data[2]};
    }

    struct color
    {
        static const vmath::vec4 AliceBlue;
        static const vmath::vec4 AntiqueWhite;
        static const vmath::vec4 Aqua;
        static const vmath::vec4 Aquamarine;
        static const vmath::vec4 Azure;
        static const vmath::vec4 Beige;
        static const vmath::vec4 Bisque;
        static const vmath::vec4 Black;
        static const vmath::vec4 BlanchedAlmond;
        static const vmath::vec4 Blue;
        static const vmath::vec4 BlueViolet;
        static const vmath::vec4 Brown;
        static const vmath::vec4 BurlyWood;
        static const vmath::vec4 CadetBlue;
        static const vmath::vec4 Chartreuse;
        static const vmath::vec4 Chocolate;
        static const vmath::vec4 Coral;
        static const vmath::vec4 CornflowerBlue;
        static const vmath::vec4 Cornsilk;
        static const vmath::vec4 Crimson;
        static const vmath::vec4 Cyan;
        static const vmath::vec4 DarkBlue;
        static const vmath::vec4 DarkCyan;
        static const vmath::vec4 DarkGoldenRod;
        static const vmath::vec4 DarkGray;
        static const vmath::vec4 DarkGreen;
        static const vmath::vec4 DarkKhaki;
        static const vmath::vec4 DarkMagenta;
        static const vmath::vec4 DarkOliveGreen;
        static const vmath::vec4 DarkOrange;
        static const vmath::vec4 DarkOrchid;
        static const vmath::vec4 DarkRed;
        static const vmath::vec4 DarkSalmon;
        static const vmath::vec4 DarkSeaGreen;
        static const vmath::vec4 DarkSlateBlue;
        static const vmath::vec4 DarkSlateGray;
        static const vmath::vec4 DarkTurquoise;
        static const vmath::vec4 DarkViolet;
        static const vmath::vec4 DeepPink;
        static const vmath::vec4 DeepSkyBlue;
        static const vmath::vec4 DimGray;
        static const vmath::vec4 DodgerBlue;
        static const vmath::vec4 FireBrick;
        static const vmath::vec4 FloralWhite;
        static const vmath::vec4 ForestGreen;
        static const vmath::vec4 Fuchsia;
        static const vmath::vec4 Gainsboro;
        static const vmath::vec4 GhostWhite;
        static const vmath::vec4 Gold;
        static const vmath::vec4 GoldenRod;
        static const vmath::vec4 Gray;
        static const vmath::vec4 Green;
        static const vmath::vec4 GreenYellow;
        static const vmath::vec4 HoneyDew;
        static const vmath::vec4 HotPink;
        static const vmath::vec4 IndianRed;
        static const vmath::vec4 Indigo;
        static const vmath::vec4 Ivory;
        static const vmath::vec4 Khaki;
        static const vmath::vec4 Lavender;
        static const vmath::vec4 LavenderBlush;
        static const vmath::vec4 LawnGreen;
        static const vmath::vec4 LemonChiffon;
        static const vmath::vec4 LightBlue;
        static const vmath::vec4 LightCoral;
        static const vmath::vec4 LightCyan;
        static const vmath::vec4 LightGoldenRodYellow;
        static const vmath::vec4 LightGray;
        static const vmath::vec4 LightGreen;
        static const vmath::vec4 LightPink;
        static const vmath::vec4 LightSalmon;
        static const vmath::vec4 LightSeaGreen;
        static const vmath::vec4 LightSkyBlue;
        static const vmath::vec4 LightSlateGray;
        static const vmath::vec4 LightSteelBlue;
        static const vmath::vec4 LightYellow;
        static const vmath::vec4 Lime;
        static const vmath::vec4 LimeGreen;
        static const vmath::vec4 Linen;
        static const vmath::vec4 Magenta;
        static const vmath::vec4 Maroon;
        static const vmath::vec4 MediumAquaMarine;
        static const vmath::vec4 MediumBlue;
        static const vmath::vec4 MediumOrchid;
        static const vmath::vec4 MediumPurple;
        static const vmath::vec4 MediumSeaGreen;
        static const vmath::vec4 MediumSlateBlue;
        static const vmath::vec4 MediumSpringGreen;
        static const vmath::vec4 MediumTurquoise;
        static const vmath::vec4 MediumVioletRed;
        static const vmath::vec4 MidnightBlue;
        static const vmath::vec4 MintCream;
        static const vmath::vec4 MistyRose;
        static const vmath::vec4 Moccasin;
        static const vmath::vec4 NavajoWhite;
        static const vmath::vec4 Navy;
        static const vmath::vec4 OldLace;
        static const vmath::vec4 Olive;
        static const vmath::vec4 OliveDrab;
        static const vmath::vec4 Orange;
        static const vmath::vec4 OrangeRed;
        static const vmath::vec4 Orchid;
        static const vmath::vec4 PaleGoldenRod;
        static const vmath::vec4 PaleGreen;
        static const vmath::vec4 PaleTurquoise;
        static const vmath::vec4 PaleVioletRed;
        static const vmath::vec4 PapayaWhip;
        static const vmath::vec4 PeachPuff;
        static const vmath::vec4 Peru;
        static const vmath::vec4 Pink;
        static const vmath::vec4 Plum;
        static const vmath::vec4 PowderBlue;
        static const vmath::vec4 Purple;
        static const vmath::vec4 RebeccaPurple;
        static const vmath::vec4 Red;
        static const vmath::vec4 RosyBrown;
        static const vmath::vec4 RoyalBlue;
        static const vmath::vec4 SaddleBrown;
        static const vmath::vec4 Salmon;
        static const vmath::vec4 SandyBrown;
        static const vmath::vec4 SeaGreen;
        static const vmath::vec4 SeaShell;
        static const vmath::vec4 Sienna;
        static const vmath::vec4 Silver;
        static const vmath::vec4 SkyBlue;
        static const vmath::vec4 SlateBlue;
        static const vmath::vec4 SlateGray;
        static const vmath::vec4 Snow;
        static const vmath::vec4 SpringGreen;
        static const vmath::vec4 SteelBlue;
        static const vmath::vec4 Tan;
        static const vmath::vec4 Teal;
        static const vmath::vec4 Thistle;
        static const vmath::vec4 Tomato;
        static const vmath::vec4 Turquoise;
        static const vmath::vec4 Violet;
        static const vmath::vec4 Wheat;
        static const vmath::vec4 White;
        static const vmath::vec4 WhiteSmoke;
        static const vmath::vec4 Yellow;
        static const vmath::vec4 YellowGreen;
    };

    inline vmath::vec4 GetColorVec4FromColorName(const std::string& ColorName)
    {
        const static std::unordered_map<std::string, vmath::vec4> ColorNameToVec4UnorderedMap =
        {
            { "AliceBlue", color::AliceBlue },
            { "AntiqueWhite", color::AntiqueWhite },
            { "Aqua", color::Aqua },
            { "Aquamarine", color::Aquamarine },
            { "Azure", color::Azure },
            { "Beige", color::Beige },
            { "Bisque", color::Bisque },
            { "Black", color::Black },
            { "BlanchedAlmond", color::BlanchedAlmond },
            { "Blue", color::Blue },
            { "BlueViolet", color::BlueViolet },
            { "Brown", color::Brown },
            { "BurlyWood", color::BurlyWood },
            { "CadetBlue", color::CadetBlue },
            { "Chartreuse", color::Chartreuse },
            { "Chocolate", color::Chocolate },
            { "Coral", color::Coral },
            { "CornflowerBlue", color::CornflowerBlue },
            { "Cornsilk", color::Cornsilk },
            { "Crimson", color::Crimson },
            { "Cyan", color::Cyan },
            { "DarkBlue", color::DarkBlue },
            { "DarkCyan", color::DarkCyan },
            { "DarkGoldenRod", color::DarkGoldenRod },
            { "DarkGray", color::DarkGray },
            { "DarkGreen", color::DarkGreen },
            { "DarkKhaki", color::DarkKhaki },
            { "DarkMagenta", color::DarkMagenta },
            { "DarkOliveGreen", color::DarkOliveGreen },
            { "DarkOrange", color::DarkOrange },
            { "DarkOrchid", color::DarkOrchid },
            { "DarkRed", color::DarkRed },
            { "DarkSalmon", color::DarkSalmon },
            { "DarkSeaGreen", color::DarkSeaGreen },
            { "DarkSlateBlue", color::DarkSlateBlue },
            { "DarkSlateGray", color::DarkSlateGray },
            { "DarkTurquoise", color::DarkTurquoise },
            { "DarkViolet", color::DarkViolet },
            { "DeepPink", color::DeepPink },
            { "DeepSkyBlue", color::DeepSkyBlue },
            { "DimGray", color::DimGray },
            { "DodgerBlue", color::DodgerBlue },
            { "FireBrick", color::FireBrick },
            { "FloralWhite", color::FloralWhite },
            { "ForestGreen", color::ForestGreen },
            { "Fuchsia", color::Fuchsia },
            { "Gainsboro", color::Gainsboro },
            { "GhostWhite", color::GhostWhite },
            { "Gold", color::Gold },
            { "GoldenRod", color::GoldenRod },
            { "Gray", color::Gray },
            { "Green", color::Green },
            { "GreenYellow", color::GreenYellow },
            { "HoneyDew", color::HoneyDew },
            { "HotPink", color::HotPink },
            { "IndianRed", color::IndianRed },
            { "Indigo", color::Indigo },
            { "Ivory", color::Ivory },
            { "Khaki", color::Khaki },
            { "Lavender", color::Lavender },
            { "LavenderBlush", color::LavenderBlush },
            { "LawnGreen", color::LawnGreen },
            { "LemonChiffon", color::LemonChiffon },
            { "LightBlue", color::LightBlue },
            { "LightCoral", color::LightCoral },
            { "LightCyan", color::LightCyan },
            { "LightGoldenRodYellow", color::LightGoldenRodYellow },
            { "LightGray", color::LightGray },
            { "LightGreen", color::LightGreen },
            { "LightPink", color::LightPink },
            { "LightSalmon", color::LightSalmon },
            { "LightSeaGreen", color::LightSeaGreen },
            { "LightSkyBlue", color::LightSkyBlue },
            { "LightSlateGray", color::LightSlateGray },
            { "LightSteelBlue", color::LightSteelBlue },
            { "LightYellow", color::LightYellow },
            { "Lime", color::Lime },
            { "LimeGreen", color::LimeGreen },
            { "Linen", color::Linen },
            { "Magenta", color::Magenta },
            { "Maroon", color::Maroon },
            { "MediumAquaMarine", color::MediumAquaMarine },
            { "MediumBlue", color::MediumBlue },
            { "MediumOrchid", color::MediumOrchid },
            { "MediumPurple", color::MediumPurple },
            { "MediumSeaGreen", color::MediumSeaGreen },
            { "MediumSlateBlue", color::MediumSlateBlue },
            { "MediumSpringGreen", color::MediumSpringGreen },
            { "MediumTurquoise", color::MediumTurquoise },
            { "MediumVioletRed", color::MediumVioletRed },
            { "MidnightBlue", color::MidnightBlue },
            { "MintCream", color::MintCream },
            { "MistyRose", color::MistyRose },
            { "Moccasin", color::Moccasin },
            { "NavajoWhite", color::NavajoWhite },
            { "Navy", color::Navy },
            { "OldLace", color::OldLace },
            { "Olive", color::Olive },
            { "OliveDrab", color::OliveDrab },
            { "Orange", color::Orange },
            { "OrangeRed", color::OrangeRed },
            { "Orchid", color::Orchid },
            { "PaleGoldenRod", color::PaleGoldenRod },
            { "PaleGreen", color::PaleGreen },
            { "PaleTurquoise", color::PaleTurquoise },
            { "PaleVioletRed", color::PaleVioletRed },
            { "PapayaWhip", color::PapayaWhip },
            { "PeachPuff", color::PeachPuff },
            { "Peru", color::Peru },
            { "Pink", color::Pink },
            { "Plum", color::Plum },
            { "PowderBlue", color::PowderBlue },
            { "Purple", color::Purple },
            { "RebeccaPurple", color::RebeccaPurple },
            { "Red", color::Red },
            { "RosyBrown", color::RosyBrown },
            { "RoyalBlue", color::RoyalBlue },
            { "SaddleBrown", color::SaddleBrown },
            { "Salmon", color::Salmon },
            { "SandyBrown", color::SandyBrown },
            { "SeaGreen", color::SeaGreen },
            { "SeaShell", color::SeaShell },
            { "Sienna", color::Sienna },
            { "Silver", color::Silver },
            { "SkyBlue", color::SkyBlue },
            { "SlateBlue", color::SlateBlue },
            { "SlateGray", color::SlateGray },
            { "Snow", color::Snow },
            { "SpringGreen", color::SpringGreen },
            { "SteelBlue", color::SteelBlue },
            { "Tan", color::Tan },
            { "Teal", color::Teal },
            { "Thistle", color::Thistle },
            { "Tomato", color::Tomato },
            { "Turquoise", color::Turquoise },
            { "Violet", color::Violet },
            { "Wheat", color::Wheat },
            { "White", color::White },
            { "WhiteSmoke", color::WhiteSmoke },
            { "Yellow", color::Yellow },
            { "YellowGreen", color::YellowGreen }
        };

        return ColorNameToVec4UnorderedMap.find(ColorName)->second;
    }
}

#endif
